#!/usr/bin/env python3
"""Performance study: cost of instruction encryption and how the decrypted-
instruction cache hides it.

For every halting test program it measures cycles and CPI
  - without encryption (baseline, same pipeline and cache),
  - with AES-XEX at the paper design point (8 lines, 11-cycle AES, 4-cycle memory),
  - while varying the number of decrypted lines (1..64) and the AES latency.
Writes results/perf.csv and results/perf.md.

    python tools/sweep.py
"""
import csv
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from run_tests import find_tb  # noqa: E402

PROGRAMS = ["signature", "loop_sum", "fib", "bubble", "strings", "muldiv", "aes", "hazards", "sieve", "matmul"]


def run(tb, prog, opts):
    r = subprocess.run([str(tb), str(ROOT / "build" / "progs" / prog)] + opts, capture_output=True, text=True)
    if r.returncode:
        sys.exit(f"{prog} {opts} failed:\n{r.stdout}")
    f = dict(kv.split("=") for kv in r.stdout.split() if "=" in kv)
    return int(f["cycles"]), int(f["retired"]), int(f["decrypted"])


def main():
    tb = find_tb(None)
    rows = []
    for p in PROGRAMS:
        base_c, ret, _ = run(tb, p, ["--plain"])
        enc_c, _, dec = run(tb, p, [])
        row = {"program": p, "retired": ret, "cycles_plain": base_c, "cycles_xex": enc_c,
               "cpi_plain": round(base_c / ret, 3), "cpi_xex": round(enc_c / ret, 3),
               "overhead_pct": round(100 * (enc_c - base_c) / base_c, 1), "blocks_decrypted": dec}
        for lines in (1, 2, 4, 8, 16, 32, 64):
            c, _, _ = run(tb, p, ["--icache", str(lines)])
            row[f"cpi_lines{lines}"] = round(c / ret, 3)
        for lat in (1, 4, 11, 22, 44):
            c, _, _ = run(tb, p, ["--aes", str(lat)])
            row[f"cpi_aes{lat}"] = round(c / ret, 3)
        rows.append(row)

    out = ROOT / "results"
    out.mkdir(exist_ok=True)
    with open(out / "perf.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)

    md = ["# Performance results", "",
          "Generated by `python tools/sweep.py`. Cycle-level C simulation of the core; design point: "
          "8 decrypted lines, 11-cycle AES unit, 4-cycle instruction-memory block read.", "",
          "## Cost of encryption at the design point", "",
          "| program | instructions | CPI without encryption | CPI with AES-XEX | overhead | blocks decrypted |",
          "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for r in rows:
        md.append(f"| {r['program']} | {r['retired']} | {r['cpi_plain']:.3f} | {r['cpi_xex']:.3f} | "
                  f"{r['overhead_pct']:+.1f}% | {r['blocks_decrypted']} |")
    tot_plain = sum(r["cycles_plain"] for r in rows)
    tot_xex = sum(r["cycles_xex"] for r in rows)
    md += ["", f"All programs together: {tot_plain} cycles without encryption, {tot_xex} with AES-XEX "
               f"({100 * (tot_xex - tot_plain) / tot_plain:+.1f}%).", "",
           "## CPI against the number of decrypted lines (AES 11 cycles)", "",
           "| program | 1 | 2 | 4 | 8 | 16 | 32 | 64 |", "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
    for r in rows:
        md.append(f"| {r['program']} | " + " | ".join(f"{r[f'cpi_lines{n}']:.3f}" for n in (1, 2, 4, 8, 16, 32, 64)) + " |")
    md += ["", "## CPI against the AES latency (8 lines)", "",
           "| program | 1 | 4 | 11 | 22 | 44 |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for r in rows:
        md.append(f"| {r['program']} | " + " | ".join(f"{r[f'cpi_aes{n}']:.3f}" for n in (1, 4, 11, 22, 44)) + " |")
    (out / "perf.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
